apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

# If you’re on modern kustomize, prefer `patches` (it supersedes patchesStrategicMerge)
patches:
  - path: replicas.yaml
    target:
      kind: Deployment
      name: mywebapp

configMapGenerator:
  - name: mykustom-map
    env: config.properties
